version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "aws-cloud-resume"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-229dk7h6pvvt"
s3_prefix = "aws-cloud-resume"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
disable_rollback = true
